combine_control_expr = false
edition = "2021"
format_macro_matchers = true
match_block_trailing_comma = true
imports_granularity = "Module"
newline_style = "Unix"
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
version = "Two"
