[package]
name = "nate"
version = "0.1.9"
edition = "2021"
authors = ["René Kijewski <crates.io@k6i.de>"]
license = "Apache-2.0"
description = "Not a Template Engine. Derive Display using a template."
homepage = "https://github.com/Kijewski/nate"
repository = "https://github.com/Kijewski/nate"
categories = ["template-engine"]
keywords = ["html", "template", "no-std"]
readme = "README.md"

[dependencies]
nate-common = { path = "../nate-common", version = "0.1.9", default-features = false }
nate-derive = { path = "../nate-derive", version = "0.1.9", default-features = false }

[features]
default = ["std"]
alloc = ["nate-common/alloc"]
std = ["nate-common/std"]
doc_cfg = ["nate-common/doc_cfg"]
