name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: "58 7 * * 4"

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: check
          toolchain: nightly
          components: rustfmt

      - run: cargo fmt --all -- --check

  check:
    strategy:
      matrix:
        toolchain:
          - "1.53"
          - stable
          - nightly

    name: "Check/${{ matrix.toolchain }}"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: check
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - run: cargo check --workspace --all-targets

      - run: cargo clippy --all-targets -- -D warnings

  test:
    strategy:
      matrix:
        toolchain:
          - "1.53"
          - stable
          - nightly

    name: "Test/${{ matrix.toolchain }}"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: test
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - run: cargo test --workspace --all-targets

  doc:
    name: "Documentation"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: doc
          toolchain: nightly
          components: clippy

      - run: cargo doc --workspace --features docsrs

  audit:
    runs-on: ubuntu-latest

    name: "Cargo audit"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: audit
          toolchain: stable
          components: clippy

      - name: Audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
