name: CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: "58 7 * * 4"

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: fmt
          toolchain: nightly
          components: rustfmt

      - run: cargo fmt --all -- --check

  clippy:
    strategy:
      matrix:
        toolchain:
          - "1.56"
          - stable
          - beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: check
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - run: cargo clippy --all-targets -- -D warnings

  check:
    strategy:
      matrix:
        toolchain:
          - "1.56"
          - stable
          - beta
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: check
          toolchain: ${{ matrix.toolchain }}

      - run: cargo check --workspace --all-targets

  test:
    strategy:
      matrix:
        toolchain:
          - "1.56"
          - stable
          - beta
        os:
          - ubuntu-20.04
          - windows-2022
          - macos-12
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      # Use old clang when needed.
      # See https://github.com/strawlab/iana-time-zone/pull/79
      - uses: maxim-lobanov/setup-xcode@v1
        if: matrix.os == 'macos-12' && matrix.toolchain == '1.56'
        with:
          xcode-version: "13.4.1"

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: test
          toolchain: ${{ matrix.toolchain }}
          components: clippy

      - run: cargo test --workspace --all-targets


  minimum-versions:
    strategy:
      matrix:
        toolchain:
          - "1.56"
          - stable
          - beta
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: minimum-versions
          toolchain: ${{ matrix.toolchain }}

      - run: RUSTC_BOOTSTRAP=1 cargo generate-lockfile -Zminimal-versions

      - run: cargo test --all-targets --package nate -- --show-output

  doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: doc
          toolchain: nightly

      - run: RUSTDOCFLAGS="-D warnings --cfg docsrs" cargo +nightly doc --no-deps

  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: doc
          toolchain: stable

      - run: cargo package --package nate

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: ./.github/actions/setup-rust
        with:
          key: audit
          toolchain: stable

      - name: Audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
